---
title: "Dzień 3 - Regresja - zadania"
author: "Marcin K. Dyderski, Patryk Czortek"
date: "3 kwietnia 2019"
output: pdf_document
---

## Zadania do wykonania

1. Z GitHuba pobierz dataset z cechami roślin, link: [https://github.com/mkdyderski/BSS/blob/BSS2019/datasety/vege_1517_traits.csv]. Możesz również ściągnąć go do R za pomocą funkcji `read.csv()`:
```{r, eval=FALSE}
baza<-read.csv('https://raw.githubusercontent.com/mkdyderski/BSS/BSS2019/datasety/vege_1517_traits.csv',sep=';')
```

1. Wczytaj plik ‘prunus.csv’ dostepny na githubie. Zawiera on dane wykorzystane w pracy Dyderski i Jagodzinski 2015 https://www.forestry.actapol.net/pub/2_2_2015.pdf. Opis zmiennych: a - zwarcie warstwy drzew (%) b - zwarcie warstwy krzewów (%) c - pokrycie runa zielnego (%) d - pokrycie warstwy mszystej (%) prunusc - liczba osobników czeremchy w warstwie zielnej, prunusb - liczba osobników czeremchy w warstwie krzewów, richness - bogactwo gatunkowe runa, shannon - wskaźnik różnorodności Shannona dla runa, L - wskaźnik świetlny Ellenberga (1-9, 1-cień, 9-pełne słońce), M - wskaźnik wilgotności Ellenberga (1-12, 1- pustynia, 12 - rośliny zanurzone), SR - wskaźnik odczynu gleby (1-9, 1-kwaśne, 9-lekko zasadowe, 7- obojętne), N - wskaźnik żyznosci (1-9, 1-ubogie, 9-bardzo żyzne)

2. Sprawdź które kolumny zawierają zmienne liczbowe, a które tekstowe
3. Wykonaj histogram dla seed_mass
4. Wykonaj tabelę dwudzielczą growth_from oraz strategy - czy widać jakieś zależności?
5. Wykonaj boxploty dla seed_mass w ramach strategy 
6. Podaj srednie wartosci kilku wybranych cech dla grup hg (historyczno-geograficznych) i wykonaj wykres słupkowy (srednie + SE)

7. Wczytaj *własny zbiór danych* i poznaj jego strukturę - jakie rozkłady mają poszczególne zmienne?
8. Wykonaj wykres punktowy pokazujący relacje pomiędzy cechami dla których zakładasz występowanie pewnych zależności, dodaj linię trendu i oceń czy jest w miarę sensownie dopasowana. W przypadku wątpliwosci poproś prowadzących o podpowiedź odnośnie typu linii trendu. Możesz zestawić np. sukces reprodukcyjny z cechami środowiska czy występowanie gatunków (0-1) z dostępnością zasobów.  
9. Sprawdź czy zmienne liczbowe różnią sie pomiędzy grupami (bez testów, na razie tylko wizualnie). Możesz np. sprawdzić bogactwo gatunkowe w różnych wariantach, wartości odbicia widma dla różnych gatunków, masę czy wielkość prób dla różnych terminów lub indeks heterotermii dla różnych osobników.
10. Sprawdź, czy proste przeliczenie pozwoli dać Ci kolejną cechę do analiz. Być może wystarczy podzielić masę przez objętość by zyskać gęstość? Albo określić udział gildii/grup funkcjonalnych organizmów? Spróbuj wykorzystać do tego pakiet dplyr.
11. Przygotuj zestawienie liczebności prób w różnych wariantach za pomocą wykresów słupkowych - takie aby móc łatwo opowiedzieć o układzie badań.
