---
title: "Dzień 5 - Ordynacja - zadania"
author: "Patryk Czortek, Marcin K. Dyderski"
date: "14 stycznia 2022"
output: pdf_document
---
## Zadanie do wykonania
Tom M. Riddle badał skład gatunkowy różnych grup bezkręgowców wodnych strefy pływów: wieloszczety, skorupiaki, mięczaki i owady (plik` bezkregowce.spp.csv`) w zależności od temperatury (temperature), wysokości poziomu wody (NAP) i średnicy ziaren piasku (grainsize) – plik `bezkregowce.env.csv`

Możesz ściągnąć go do R za pomocą funkcji `read.csv()`:
```{r, eval=FALSE}
bezkregowce<-read.csv('https://raw.githubusercontent.com/mkdyderski
                      /BSS/BSS2019/datasety/bezkregowce.spp.csv',
                      sep=';',dec=',')
cechen<-read.csv('https://raw.githubusercontent.com/mkdyderski/BSS
                 /BSS2019/datasety/bezkregowce.env.csv', 
                 sep=';', dec=',')
```

a)	Na podstawie długości gradientu (z analizy DCA) ocenić, która analiza bezpośrednia (RDA czy CCA) będzie najodpowiedniejsza do analizy powyższych danych. 
b)	Przeprowadź transformację danych zawierających skład gatunkowy bezkręgowców (`decostand()`) przy użyciu różnych metod transformacji. Która transformacja Twoim zdaniem najlepiej obrazuje różnice w składzie gatunkowym?
c)	Dla danych przetransformowanych wybraną metodą przeprowadź analizy RDA i CCA. Wyniki zobrazuj w postaci wykresu przy użyciu pakietu `ggplot2` z aktywnie nałożonymi zmiennymi środowiskowymi (plik `bezkregowce.env.csv`). d)	Przy użyciu funkcji `vif.cca()` wskaż które predyktory mają największe wartości VIF (powyżej 10) dla obu analiz.
e) Za pomocą funkcji `step.cca()` sprawdź które zmienne powinny znaleźć się w modelu finalnym dla obu analiz. 
f)	Stwórz modele finalne dla obu analiz. Wykonaj dla nich analizę PERMANOVA (funkcja `anova.cca()`). Które predyktory istotnie wpływają na skład gatunkowy bezkręgowców?

##Propozycje do pracy z własnym zbiorem danych
2. Jakiego typu orynację można wykorzystać w Twoich danych? Czy może być przydatna do testowania hipotez? Czy jako metoda eksploracyjna, pokazująca jak zmienia się kompozycja gatunkowa w gradientach? Jeśli nie badasz zbiorowisk/zgrupowań zastanów się nad wykorzystaniem PCA/CA jako metody eksploracyjnej analizy danych zamiast macierzy korelacji. Wykonaj prostą ordynacje na danych wycentrowanych lub standaryzowanych.
